name = "promtoy"
pages_build_output_dir = "dist"
compatibility_date = "2024-02-21"

[[d1_databases]]
binding = "DB" # Ini harus sama dengan env.DB di fungsi typescript
database_name = "promtoy"
database_id = "26ebaff4-98b3-41d7-86b9-6887873d261b"
preview_database_id = "DB" # Diperlukan untuk local development

[[r2_buckets]]
binding = "ASSETS_BUCKET" # Sama dengan env.ASSETS_BUCKET
bucket_name = "ugc-assets"
preview_bucket_name = "ugc-assets-preview" # Diperlukan untuk local development